owner: choipureum 
repo: ServerStatus 

sites: 
  - name: Desktop_Outline_API
    url: $SECRET_SITE_1
    method: GET
    expectedStatusCodes:
      - 404
    __dangerous__insecure: true
    
  - name: MBC_App_v4.0.0
    url: http://m.imbc.com/wiz/mbcapp/home.html?isAuto=Y
        
assignees: 
  - choipureum
  
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /ServerStatus
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /ServerStatus/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
