owner: choipureum 
repo: ServerStatus 

sites: 
  - name: Desktop_Outline_API
    url: $SECRET_SITE_1
    method: GET
    expectedStatusCodes:
      - 404
    __dangerous__insecure: true
    
  - name: MBC_App_v4.0.0
    url: https://m.imbc.com/wiz/mbcapp/v2/main.html?isAuto=Y
    expectedStatusCodes:
      - 200
 
  - name: MBC_control_API
    url: https://control.imbc.com/App/V2/Timeline
    icon: https://favicons.githubusercontent.com/m.imbc.com
    method: GET
    expectedStatusCodes:
      - 200
      
  - name: Olympic_API
    url: https://control.imbc.com/WebApi/OlympicsRank
    icon: https://favicons.githubusercontent.com/m.imbc.com
    method: GET
    expectedStatusCodes:
      - 200
    
  - name: Corona-19_API
    url: https://control.imbc.com/WebApi/Covid19
    icon: https://favicons.githubusercontent.com/m.imbc.com
    method: GET
    expectedStatusCodes:
      - 200
   
  - name: 랜덤_할일_생성기_v1.0
    url: https://choipureum.github.io/todo-generator
    method: GET
    expectedStatusCodes:
      - 200


assignees: 
  - choipureum
  
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /ServerStatus
  logoUrl: http://with.mbc.co.kr/images/ci_hmi_v2_08.jpg
  name: Munhwa BroadCast Project
  navbar:
    - title: Status
      href: /ServerStatus/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

notifications:
  - type: slack
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
