owner: choipureum 
repo: ServerStatus 

sites: 
  - name: 실패 테스트 사이트
    url: $SECRET_SITE_1
    method: GET
    expectedStatusCodes:
      - 404
    __dangerous__insecure: true
    
  - name: MBC_App_v4.5.1
    url: https://m.imbc.com/wiz/mbcapp/v3/index.html?isAuto=Y
    expectedStatusCodes:
      - 200
 
  - name: DDD8 Exit Server
    url: https://exitnow.link/swagger-ui/#/
    method: GET
    expectedStatusCodes:
      - 200


assignees: 
  - choipureum
  
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /ServerStatus
  logoUrl: http://with.mbc.co.kr/images/ci_hmi_v2_08.jpg
  name: Munhwa BroadCast Project
  navbar:
    - title: Status
      href: /ServerStatus/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

notifications:
  - type: slack
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
